# Generated by Django 3.2.5 on 2022-12-02 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chronology',
            name='descrition',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
