# Generated by Django 3.2.5 on 2022-12-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0003_auto_20221203_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='chronology',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='chronology',
            name='descrition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
