# Generated by Django 3.2.5 on 2022-12-17 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0006_auto_20221214_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chronology',
            old_name='descrition',
            new_name='description',
        ),
    ]
