# Generated by Django 3.2.5 on 2022-12-21 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chronology', '0007_rename_descrition_chronology_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.JSONField()),
                ('name', models.CharField(max_length=64)),
                ('user_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronology.userregion')),
            ],
        ),
        migrations.AddField(
            model_name='regiondata',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chronology.style'),
        ),
    ]
